### ISSUE TITLE
Add Rust

### ISSUE THREAD

**Issue by swise0** [pieroxy/lz-string#157]
Add support for the Rust Programming Language

**Comment by Rycochet** [comment]
This is a Javascript library - if you find a compatible Rust library then it can be linked to in the Readme

**Comment by pieroxy** [comment]
Hello. As stated by Rycochet, this is a JavaScript library.

Writing a port to Rust should be trivial and only take a couple of hours (providing you're proficient in Rust). Instructions to do so are here: https://pieroxy.net/blog/pages/lz-string/index.html#inline_menu_7

If you ever get to do it, please open another issue here so that we can link your implementation in the readme.

I'll close this issue now as this is off topic.
