### ISSUE TITLE
How does lz-string compare to platform `CompressionStream`?

### ISSUE THREAD

**Issue by Fuzzyma** [pieroxy/lz-string#271]
I am wondering if the functionality of lz-string can be nowadays mirrored by a CompressionStream.

Can anyone weight in on that topic? I naively compressed a bit of html using gzip and converted it to a format I can use in the url (since thats what i need) and the compression ratio of lz-string was about 1.5 while my naive version had 2.26.

Totally possible that I did something wrong but I wanna know if you people know of any downsides in regard of CompressionStream or any upsides with lz-string.

**Comment by JobLeonard** [comment]
Well, if you already managed to implement it then it sounds like you already answered your own question about viability!

Out of curiosity: did you use [`TextDecoderStream`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoderStream), so the strings were encoded into utf8 bytes instead of utf16? I bet that would compress better than `new Blob([str]).stream()`, which I've seen in [some blogs](https://evanhahn.com/javascript-compression-streams-api-with-strings/).

But if you're asking for some thoughts on when to consider either, well, of the top of my head:

- how much backwards compatibility do you need for which browsers? See https://caniuse.com/?search=compressionstream. Having said that, I have a few spare ancient smartphones that no longer receive official security updates, but still have recent browsers. But maybe your clients are stuck on old MacBooks with old versions of Safari or something.
- perhaps surprisingly, I've noticed in tests that for (very) short strings, lz-string sometimes has the compression advantage over deflate and gzip (mainly due to the format of the latter two bringing some small constant overhead). Of course, that's a matter of case-by-case benchmarking with realistic input, which in your case already seems to be in favor of `CompressionStream`. It might be worth remembering in future projects.

But those are two hypotheticals, based on what you've shared I can't think of any obvious reason why you shouldn't use the `CompressionStream` api in your case :)

(EDIT: Oh, and CS is `async` of course, which can be nice or annoying depending on the circumstances, but that seems more of a convenience issue)

**Comment by JobLeonard** [comment]
Oh, one last possible concern: performance! Both in terms of computation and memory.

[That blog example](https://evanhahn.com/javascript-compression-streams-api-with-strings/) I linked to shows that this API naturally uses lots of `Uint8Arrays`, which makes perfect sense given its intended use-case. Now, I love typed arrays, but they have a few gotchase:

- allocating them is surprisingly slow compared to plain arrays. I have been told because `ArrayBuffer` always makes a call to `malloc` or its equivalent.
- compared to other JS objects they have a bigger fixed overhead (see [this SO answer by a V8 developer](https://stackoverflow.com/a/45808835/3211791)).

The most efficient way to use TAs is to allocate a few big ones up front and re-use them as much as possible.

So if your use-case is one where you need to compress and decompress lots of small data all the time, that bottleneck of typed array allocation might become a problem, in which case LZ-string can be faster. I don't see a realistic reason why you'd want to update a url in real-time though, so if this comes up the better fix is likely to add a debouncer to your `CompressionStream`-to-URI conversion.

**Comment by Fuzzyma** [comment]
Thanks, that is helping indeed! I just wanted to make sure that I am not crazy :D.

The way my naive example (that only compresses and never decompresses lol) is working is something along this lines:

```js
async function compressWithGzip(input, format) {
  const encoder = new TextEncoder();
  const data = encoder.encode(input);

  const stream = new ReadableStream({
    start(controller) {
      controller.enqueue(data);
      controller.close();
    },
  });

  const gzipStream = new CompressionStream("gzip");
  const compressedStream = stream.pipeThrough(gzipStream);
  const chunks = [];

  const reader = compressedStream.getReader();
  let totalSize = 0;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }

  let text = "";
  for (const chunk of chunks) {
    text += await bufferToBase64(chunk);
  }

  return encodeURIComponent(text);
}
```

You can see some glaring issues right away because I am just concatenating base64 chunks and have no way to reconstruct :D. Just wanted to get a rough number of the compression I can achieve with that.

TextDecoder seems to convert input usinhg utf-8. I guess I could have used TextEncoderStream as well by creating a readable stream from input and pipe it through TextEncoderStream. 

Would be cool to have a base64TransformStream :D

// EDIT: Yes, I thought about perfromance, too. In my case it doesnt matter but I wouldnt be surprised if all that allocating and converting is hurting speed

**Comment by JobLeonard** [comment]
Oh right, I meant `TextEncoder`/`TextEncoderStream`, not `TextDecoder`/`TextDecoderStream` (I always mix up the two).

> You can see some glaring issues right away because I am just concatenating base64 chunks and have no way to reconstruct :D. Just wanted to get a rough number of the compression I can achieve with that.

Heh, well if you want a second opinion: sure, it's incomplete, but I see no obvious reason why it would not give decent ballpark figures, or otherwise overlook important issues as a first sanity test.

**Comment by Fuzzyma** [comment]
Had another little session and fixed up those bugs. base64 alignment is annoying :D.
But it seems to work now and the compression ratio is 2.27 which is neat.

Will see where I go from here. Thanks for your insights and opinions :D
