### ISSUE TITLE
Version 1.4.3 doesn't seem to be on bower

### ISSUE THREAD

**Issue by nathggns** [pieroxy/lz-string#53]
Trying to install version 1.4.3 via bower doesn't seem to work. Crucially, this is the version that seems to add support for AMD, which we need.

**Comment by pieroxy** [comment]
Working on it

**Comment by pieroxy** [comment]
Any idea how to publish it on bower? When I search for "lz-string" on bower.io, it shows lz-string updated 5 days ago which is about the same date at which I updated my bower.json file...

**Comment by nathggns** [comment]
I think you just have to make a new tag? I'm not sure, but when you install
from bower it's definitely not the latest version

On 26 April 2015 at 19:42, pieroxy <notifications@github.com> wrote:

> Any idea how to publish it on bower? When I search for "lz-string" on
> bower.io, it shows lz-string updated 5 days ago which is about the same
> date at which I updated my bower.json file...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pieroxy/lz-string/issues/53#issuecomment-96419034>.
>



-- 
Thanks,
Nathaniel Higgins
http://nath.is
@nathggns <http://twitter.com/nathggns>

**Comment by pieroxy** [comment]
You're right, I forgot to create the GitHub release tag. Sorry about that. This is done.

**Comment by pieroxy** [comment]
Can you let me know if everything is alright on your end? Also - could you update the README.md with the instructions on how to install lz-string with bower? Duplicate the "Install via npm" section and just post it as a comment here so I can copy/paste it in README.md. Otherwise I'll do it myself but I don't use bower so I might screw it up.
