### ISSUE TITLE
Question about Websocket Performance ~

### ISSUE THREAD

**Issue by McFarts** [pieroxy/lz-string#61]
I use this to compress my string data across my websocket pipe for my online action rpg game.

For example, a players inventory data can be around 2500 bytes long, but when I compress the JSON format, it returns about less than half of that which is amazing!:

![](https://i.gyazo.com/b8124955e82d750eb35a604593652d8f.png)

My question is.. I should only use this for large amounts of data that needs to be loaded into the buffer once right? I shouldn't be converting and decompressing every little thing all the time, right? Is there a way where I can increase the SPEED AMOUNT of compress drastically but still retain atleast half of the original size? In other words, If I could save more milliseconds per compression and use a bit more bytes (bandwidth) I'm fine with that.

Thank you ~

**Comment by pieroxy** [comment]
The compression and decompression time mostly is linear and depends on the size of the String (for small strings that is). So using it to compress and decompress small strings should be extra fast. In my opinion, either you compress everything because size matters for you or you don't compress anything. That's my opinion, you may choose to do something else.

**Comment by McFarts** [comment]
@pieroxy  Thank you. I did some testing in nodejs with a large json object, and lzstring performed roughly the same speed as:

http://stackoverflow.com/a/294421/1254837

..and it compresses it smaller as well.

Another question @pieroxy, would the compressToUTF16 be fine for users running a web browser under linux, or a different os? UTF16 should work fine on most modern browsers right?

**Comment by pieroxy** [comment]
UTF16 compression works on all browsers I've been able to put my hands on. iOS, Android, Windows, Mac, Linux for IE, Safari, Chrome, Firefox. They all work. This is the preferred way to store stuff in localStorage / IndexedDB, ... locally in the browser.

If you need the data to be sent outside the browser, things are different. I don't know about websockets much, but I know that a regular POST is often converted tp UTF-8 by many browsers, even if you specify UTF-16 as the encoding.

Since you are working with websockets, just make sure there is no conversion going on btw your browser and your server. If not, you should be fine. If you encounter issues, roll back to compressToEncodedURIComponent or compressToBase64.
