### ISSUE TITLE
Read compressed data without decompress

### ISSUE THREAD

**Issue by rajkumarpb** [pieroxy/lz-string#74]
Is there a way to read compressed data with compressToUTF16 directly without decompressing?

**Comment by pieroxy** [comment]
I'm not sure I understand the question... Is it for debugging purposes? Can you provide a use case?

**Comment by rajkumarpb** [comment]
Like minification!! JS Minification will strip of lot of things to make it compat but yet it is readable by code! I am asking something like this!

**Comment by pieroxy** [comment]
Most if not all webservers and browsers already implement the gzip compression. It compressed way better than this lib and is completely transparent for both the server-side and the client-side code. I don't think you want lz-string to compress your server-side JavaScript in order to read it in the browser, although it would be doable with XMLHttpRequest.
