### ISSUE TITLE
strange chars on decompression

### ISSUE THREAD

**Issue by fsimon21** [pieroxy/lz-string#77]
hello,
i'm developing a mobile app, but sometimes i have problem using decompressFromUtf16, because it works but gives strange chars on result. This problem seems to happen only on Iphone
This is what i do:
1) from Cordova app i compress (compressToUtf16) a json based string and i send it to a .net web service.
   It's a simple string with userid, password, name, etc
2) the web service takes the string, decompress it (decompressFromUtf16) and sometimes it works and sometimes not, displaying half string ok and half not, with uncomprensible chars. 
![compress](https://cloud.githubusercontent.com/assets/9480493/16624316/8069f292-43a1-11e6-9016-1eb044e2c8ae.JPG)

I'm not able to understand if the problem is on javascript compression or .NET decompression

thanks for help!

**Comment by fsimon21** [comment]
i found that the problem is in the javascript compressToUtf16, you can see the strange chars inside the compressed string ("PLU", "IND"):
![cattura](https://cloud.githubusercontent.com/assets/9480493/16650412/418b567c-443e-11e6-9d30-2dbfb679ce1a.JPG)

**Comment by pieroxy** [comment]
Can you give me a string that you cannot decompress?

**Comment by pieroxy** [comment]
On another note, the best way to determine if the problem is in the Js or C# side it to try to decompress the string in the browser before sending it to see if it works. If it works it means the JS code is able to decompress the compressed version. 

From there there could be two issues:

1. could be in the transport layer. Make sure your string is the same on the server side than it was in the client side. For the transport I recommend compressToEncodedURIComponent which only produces uri-safe characters. So make sure the compressed string in the browser is the exact same as he one on the server. 

2. There could be a bug in the C# decompression routine.

**Comment by rreghin** [comment]
Hello.

I have a very similar problem. I am not sure if the problem is when compressing or decompressing. Here are the original string I am trying to compress/decompress, and the resulting string after decompression, so you can compare and find out what the problem is.

Original string (JSON string):
[{"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "10", "IPDT_CD_ID": "570001000000000000001017", "LIST_TX_GROUPID": "", "VALUE": "2001"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "10", "IPDT_CD_ID": "570001000000000000001008", "LIST_TX_GROUPID": "", "VALUE": "2001"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "20", "IPDT_CD_ID": "570001000000000000001006", "LIST_TX_GROUPID": "", "VALUE": "56"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "20", "IPDT_CD_ID": "570001000000000000001009", "LIST_TX_GROUPID": "", "VALUE": "DOCUMENTO DE TRANSPORTE"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "30", "IPDT_CD_ID": "570001000000000000001020", "LIST_TX_GROUPID": "", "VALUE": "BOLSA"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "30", "IPDT_CD_ID": "570001000000000000001011", "LIST_TX_GROUPID": "", "VALUE": "BOLSA"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "40", "IPDT_CD_ID": "570001000000000000001012", "LIST_TX_GROUPID": "", "VALUE": "GIRARDOT"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "40", "IPDT_CD_ID": "570001000000000000001019", "LIST_TX_GROUPID": "", "VALUE": "DOCUMENTO DE TRANSPORTE"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "50", "IPDT_CD_ID": "570001000000000000001013", "LIST_TX_GROUPID": "", "VALUE": "2016-07-21"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "60", "IPDT_CD_ID": "570001000000000000001014", "LIST_TX_GROUPID": "", "VALUE": "2016-07-22"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "70", "IPDT_CD_ID": "570001000000000000001015", "LIST_TX_GROUPID": "", "VALUE": "12"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "10", "IPDT_CD_ID": "570001000000000000001008", "LIST_TX_GROUPID": "", "VALUE": "2011"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "10", "IPDT_CD_ID": "570001000000000000001017", "LIST_TX_GROUPID": "", "VALUE": "2011"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "20", "IPDT_CD_ID": "570001000000000000001009", "LIST_TX_GROUPID": "", "VALUE": "1"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "20", "IPDT_CD_ID": "570001000000000000001006", "LIST_TX_GROUPID": "", "VALUE": "123"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "30", "IPDT_CD_ID": "570001000000000000001020", "LIST_TX_GROUPID": "", "VALUE": "POS"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "30", "IPDT_CD_ID": "570001000000000000001011", "LIST_TX_GROUPID": "", "VALUE": "2"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "40", "IPDT_CD_ID": "570001000000000000001012", "LIST_TX_GROUPID": "", "VALUE": "3"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "40", "IPDT_CD_ID": "570001000000000000001019", "LIST_TX_GROUPID": "", "VALUE": "IMCO"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "50", "IPDT_CD_ID": "570001000000000000001013", "LIST_TX_GROUPID": "", "VALUE": "2016-07-21"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "60", "IPDT_CD_ID": "570001000000000000001014", "LIST_TX_GROUPID": "", "VALUE": "2016-07-21"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "70", "IPDT_CD_ID": "570001000000000000001015", "LIST_TX_GROUPID": "", "VALUE": "11"}, {"OFFSET": "2", "FILE_CD_ID": "", "DOSS_CD_ID": "", "PRDT_CD_ID": "", "ORIG_CD_ID": "", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "", "IPDT_CD_ID": "", "LIST_TX_GROUPID": "", "VALUE": ""}]

Decompressed string:
[{"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "10", "IPDT_CD_ID": "570001000000000000001017", "LIST_TX_GROUPID": "", "VALUE": "2001"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "10", "IPDT_CD_ID": "570001000000000000001008", "LIST_TX_GROUPID": "", "VALUE": "2001"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "20", "IPDT_CD_ID": "570001000000000000001006", "LIST_TX_GROUPID": "", "VALUE": "56"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "20", "IPDT_CD_ID": "570001000000000000001009", "LIST_TX_GROUPID": "", "VALUE": "DOCUMENTO DE TRANSPORTE"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "30", "IPDT_CD_ID": "570001000000000000001020", "LIST_TX_GROUPID": "", "VALUE": "BOLSA"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "30", "IPDT_CD_ID": "570001000000000000001011", "LIST_TX_GROUPID": "", "VALUE": "BOLSA"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "40", "IPDT_CD_ID": "570001000000000000001012", "LIST_TX_GROUPID": "", "VALUE": "GIRARDOT"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "40", "IPDT_CD_ID": "570001000000000000001019", "LIST_TX_GROUPID": "", "VALUE": "DOCUMENTO DE TRANSPORTE"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "50", "IPDT_CD_ID": "570001000000000000001013", "LIST_TX_GROUPID": "", "VALUE": "201607-21"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "60", "IPDT_CD_ID": "570001000000000000001014", "LIST_TX_GROUPID": "", "VALUE": "2010707-22"}, {"OFFSET": "1", "FILE_CD_ID": "570001000000000000041777", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "U", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "70", "IPDT_CD_ID": "570001000000000000001015", "LIST_TX_GROUPID": "", "VALUE": "12"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "10", "IPDT_CD_ID": "570001000000000000001008", "LIST_TX_GROUPID": "", "VALUE": "2011"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "10", "IPDT_CD_ID": "570001000000000000001017", "LIST_TX_GROUPID": "", "VALUE": "2011"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "20", "IPDT_CD_ID": "570001000000000000001009", "LIST_TX_GROUPID": "", "VALUE": "1"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "20", "IPDT_CD_ID": "570001000000000000001006", "LIST_TX_GROUPID": "", "VALUE": "123"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "30", "IPDT_CD_ID": "570001000000000000001020", "LIST_TX_GROUPID": "", "VALUE": "POS"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "30", "IPDT_CD_ID": "570001000000000000001011", "LIST_TX_GROUPID": "", "VALUE": "2"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "40", "IPDT_CD_ID": "570001000000000000001012", "LIST_TX_GROUPID": "", "VALUE": "3"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "40", "IPDT_CD_ID": "570001000000000000001019", "LIST_TX_GROUPID": "", "VALUE": "IMCO"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "50", "IPDT_CD_ID": "570001000000000000001013", "LIST_TX_GROUPID": "", "VALUE": "2010--21"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "60", "IPDT_CD_ID": "570001000000000000001014", "LIST_TX_GROUPID": "", "VALUE": "2010707-21"}, {"OFFSET": "2", "FILE_CD_ID": "570001000000000000041778", "DOSS_CD_ID": "", "PRDT_CD_ID": "570001000000000000001005", "ORIG_CD_ID": "I", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "70", "IPDT_CD_ID": "570001000000000000001015", "LIST_TX_GROUPID": "", "VALUE": "11"}, {"OFFSET": "2", "FILE_CD_ID": "", "DOSS_CD_ID": "", "PRDT_CD_ID": "", "ORIG_CD_ID": "", "FILE_TX_IRONID": "", "IPDT_NR_ORDER": "", "IPDT_CD_ID": "", "LIST_TX_GROUPID": "", "VALUE": ""}]

Note that I have tried ALL compression/decompression methods, and all gave me the same results.

Thank you very much in advance.

**Comment by zyphersworld** [comment]
@rreghin i just tested your original string  and the decompressed text was exactly the same.

i used the following code:
```
var string = 'YOUR_STRING_HERE';
console.log(string + "\n" + string.length);
var compressed = LZString.compress(string);
var stringFinal = LZString.decompress(compressed);
console.log(string + "\n" + stringFinal.length);
```

**Comment by rreghin** [comment]
@zyphersworld did you try using compressToUTF16, or any other than compress?

**Comment by pieroxy** [comment]
@rreghin I wrote a small page to test this issue: http://palmdrive.net/lzstring/

It works on every browser I have tested so far. Can you tell me if that fails on your end? Just have a look at the source code, it is dead simple.

**Comment by pieroxy** [comment]
Ok, so I was testing the wrong stuff. I fixed the page and now the test is successful in all browsers I've tested so far (linux Chrome+Firefox and my iPhone's). Can you tell me if you can get it to fail? And if so on what browser/platform ?

**Comment by pieroxy** [comment]
@fsimon21 ANy update on this issue ?

**Comment by fsimon21** [comment]
sorry for my late answer, no i haven't tried yet because i had to finish another project.
I will try with the test page you have provided, thanks!

**Comment by rreghin** [comment]
@pieroxy I forgot to mention I'm NOT running on a browser. I'm using Java JDK 1.6.0 Mozilla's Rhino JavaScript script engine.

This is an extract from the Oracle's site about it:

"Sun's implementation of JDK 6 is co-bundled with the Mozilla Rhino based JavaScript script engine. This is based on Mozilla Rhino version 1.6R2. ... " (http://docs.oracle.com/javase/6/docs/technotes/guides/scripting/programmer_guide/#jsengine)

Maybe the compression function would work 100% on newer JDKs, but I cannot update to any other version. I'm stuck to this very version JDK/JRE 1.6.0.

Could this information be of any help to you to solve the problem?

**Comment by pieroxy** [comment]
Errrr, yes, it is a great deal different. I'll be testing this and will let you know.

**Comment by rreghin** [comment]
@pieroxy, thank you for all the attention you are giving to this problem!!

I worked the problem around, changing the conflicting character with another one. I know, it´s ugly, but I needed the compression working right away.

That's what I did...

When compressing: result = LZString.compress(data.replace(/-/g,'¬'));

When decompressing: result = LZString.decompress(data).replace(/¬/g,'-');

The conflicting character seems to be the dash "-".

**Comment by dwringer** [comment]
Any update here?  Still running into the same issue running on Oracle's NetSuite servers using SuiteScript modules.  Loading the module in a browser works perfectly but when it runs on Oracle's server, several of the hyphens in strings of numbers get alternately corrupted into 0's and removed entirely.

**Comment by niteshwashivale** [comment]
Facing some issue while decompressing the string: 

ጂ邬ǁÀ鳐䍨ࣚŰ㎁᦭Ⱉ肁곳 뀯您₀ﶀीᘌͥ쯮緯각ᐴ䣱挤井㙌拾ᐮ酋ବ㒅革㴇㉸ ៏鰥狝ꌀ 瀃悀➀匀一耜퀁䖐ŕⰀ밀딂Ą鉁 Ŝƌ墒<䕹腱議耀

**Comment by pieroxy** [comment]
@niteshwashivale Can you provide the original uncompressed string ?

**Comment by pieroxy** [comment]
> @pieroxy, thank you for all the attention you are giving to this problem!!
> 
> I worked the problem around, changing the conflicting character with another one. I know, it´s ugly, but I needed the compression working right away.
> 
> That's what I did...
> 
> When compressing: result = LZString.compress(data.replace(/-/g,'¬'));
> 
> When decompressing: result = LZString.decompress(data).replace(/¬/g,'-');
> 
> The conflicting character seems to be the dash "-".

I just re-read your message. As per the documentation, DO NOT USE THE `compress` METHOD. It is buggy.

So if you cannot decompress, it's expected.

You should use `compresstoUtf16` instead.
