### ISSUE TITLE
Are base64 and UriSafe supposed to have 65 character strings?

### ISSUE THREAD

**Issue by JobLeonard** [pieroxy/lz-string#99]
```js
> "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-$".length
>> 65
> "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".length
>> 65
```
Do we need that last char? 

Also, if not, if backwards compatibility wasn't an issue, you could remove the `+` and with it, this regex from decompression:

```
    input = input.replace(/ /g, "+");
```

Something to remember if lz-string 2.0 ever comes around :P

**Comment by pieroxy** [comment]
Base64 is about encoding 64 different chars. That's 6 bits per character. But it is not really convenient to express some bits that are not a multiple of 8, because everything is a byte. So, base64 emits blocks of 4 chars, which represent 24 bits, or three bytes. So the last character is here for padding reasons.

So yes, I could have removed it and assume during the decompression that the end of the string implicitly means padding after it. But that would not have been base64 and the gain is tiny.

**Comment by JobLeonard** [comment]
Aaaah, so the 65th character is the "end of stream" character? Thanks, I couldn't find this information anywhere I looked up Base64.
